version: "2.2"

services:
  cso_demo:
    image: cso-demo-1203
    container_name: cso-demo
    ports:
      - '21180:80'
    networks:
        customize_net:
          ipv4_address: 10.0.11.223
    command: /usr/bin/supervisord -n

  waf_demo:
    image: waf-demo-1203
    container_name: waf-demo
    ports:
      - '21280:80'
    networks:
        customize_net:
          ipv4_address: 10.0.11.17
    command: /usr/bin/supervisord -n

  mysql:
    container_name: mysql-server-demo
    image: 'sameersbn/mysql:5.7.22-1'
    restart: always
    ports:
      - '20004:3306'
    environment:
     - DB_USER=admin105
     - DB_PASS=yesadmin@816
     - DB_NAME=dj93
     - DB_REMOTE_ROOT_NAME=admin007
     - DB_REMOTE_ROOT_PASS=myadmin816

    networks:
      customize_net:
        ipv4_address: 10.0.11.37

networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24


